% Paper: M.F.A. Ahmed and S.A. Vorobyov, "Collaborative beamforming for
% wireless sensor networks with Gaussian distributed sensor nodes," IEEE
% Trans. Wireless Communications, vol. 8, no. 2, pp.638-643, Feb. 2009.
% Fig 4: The CCDF of a sample beampattern for both uniform and Gaussian
% spatial distributions: phi = pi/4 and R = 3 sigma = 2.
%
%
%
% N : Number of sensor nodes
% R : Cluster radius
% V : Vairiance of the Gaussian spatial distribution corresponding to
% cluster radius R
% phi : The azimuth angle.
% P0 : Power level.
% P0dB : Power level in dB.
% CCDF_prec : The precise CCDF of the beampattern level defined for Uniform and Gaussian
% spatial distributions.
% CCDF_RayleighApp : The approx. CCDF of the beampattern level defined for Uniform and Gaussian
% spatial distributions.



clc;clear;

P0dB = -50:0;
P0 = 10.^(P0dB./10);
R = 2;
V = (R^2)/9;
phi = pi/4;
%%%%%%%%%%%%%%%%%%
N = 16;
[CCDF_prec_u_N16,CCDF_prec_g_N16,CCDF_RayleighApp_N16]=MyCCDF(N,P0,V,phi);
%%%%%%%%%%%%%%%%%
N = 256;
[CCDF_prec_u_N256,CCDF_prec_g_N256,CCDF_RayleighApp_N256]=MyCCDF(N,P0,V,phi);
%%%%%%%%%%%%%%%%%
N = 1024;
[CCDF_prec_u_N1024,CCDF_prec_g_N1024,CCDF_RayleighApp_N1024]=MyCCDF(N,P0,V,phi);

%   - - - Ploting the figure - - -

%% Create figure
figure1 = figure;
%% Create axes
axes1 = axes(...
    'FontName','Times New Roman',...
    'FontSize',30,...
    'Parent',figure1);
xlabel(axes1,'Power P_0 [dB]');
ylabel(axes1,'CCDF');
grid(axes1,'on');
hold(axes1,'all');

%% Create plot
plot1 = plot(...
    P0dB,CCDF_prec_u_N16,...
    'LineWidth',2,...
    'Color','b',...
    'Marker','square',...
    'MarkerSize',10,...
    'Parent',axes1,...
    'DisplayName',' CCDF - Uniform');

%% Create plot
plot2 = plot(...
    P0dB,CCDF_prec_g_N16,...
    'Color','r',...
    'LineWidth',2,...
    'Marker','o',...
    'MarkerSize',10,...
    'Parent',axes1,...
    'DisplayName',' CCDF - Gaussian');

%% Create plot
plot3 = plot(...
    P0dB,CCDF_RayleighApp_N16,...
    'LineStyle','-.',...
    'Color','k',...
    'LineWidth',2,...
    'Marker','x',...
    'MarkerSize',10,...
    'Parent',axes1,...
    'DisplayName','Rayleigh approximation');
%% Create plot
plot4 = plot(...
    P0dB,CCDF_prec_u_N256,...
    'LineWidth',2,...
    'Color','b',...
    'Marker','square',...
    'MarkerSize',10,...
    'Parent',axes1,...
    'DisplayName',' CCDF - Uniform');

%% Create plot
plot5 = plot(...
    P0dB,CCDF_prec_g_N256,...
    'Color','r',...
    'LineWidth',2,...
    'Marker','o',...
    'MarkerSize',10,...
    'Parent',axes1,...
    'DisplayName',' CCDF - Gaussian');

%% Create plot
plot6 = plot(...
    P0dB,CCDF_RayleighApp_N256,...
    'LineStyle','-.',...
    'Color','k',...
    'LineWidth',2,...
    'Marker','x',...
    'MarkerSize',10,...
    'Parent',axes1,...
    'DisplayName','Rayleigh approximation');
%% Create plot
plot7 = plot(...
    P0dB,CCDF_prec_u_N1024,...
    'LineWidth',2,...
    'Color','b',...
    'Marker','square',...
    'MarkerSize',10,...
    'Parent',axes1,...
    'DisplayName',' CCDF - Uniform');

%% Create plot
plot8 = plot(...
    P0dB,CCDF_prec_g_N1024,...
    'Color','r',...
    'LineWidth',2,...
    'Marker','o',...
    'MarkerSize',10,...
    'Parent',axes1,...
    'DisplayName',' CCDF - Gaussian');

%% Create plot
plot9 = plot(...
    P0dB,CCDF_RayleighApp_N1024,...
    'LineStyle','-.',...
    'Color','k',...
    'LineWidth',2,...
    'Marker','x',...
    'MarkerSize',10,...
    'Parent',axes1,...
    'DisplayName','Rayleigh approximation');

%% Create legend
legend1 = legend(...
    axes1,{' CCDF - Uniform',' CCDF - Gaussian','Rayleigh approximation'},...
    'FontName','Times New Roman',...
    'FontSize',30,...
    'Location','SouthWest');

%% Create textbox
annotation1 = annotation(...
    figure1,'textbox',...
    'Position',[0.28 0.5 0.1 0.08],...
    'LineStyle','none',...
    'FitHeightToText','off',...
    'FontName','Times New Roman',...
    'FontSize',30,...
    'String',{'N=1024'});

%% Create textbox
annotation2 = annotation(...
    figure1,'textbox',...
    'Position',[0.7 0.5 0.1 0.08],...
    'LineStyle','none',...
    'FitHeightToText','off',...
    'FontName','Times New Roman',...
    'FontSize',30,...
    'String',{'N=16'});

%% Create textbox
annotation3 = annotation(...
    figure1,'textbox',...
    'Position',[0.53 0.5 0.1 0.08],...
    'LineStyle','none',...
    'FitHeightToText','off',...
    'FontName','Times New Roman',...
    'FontSize',30,...
    'String',{'N=256'});