% Paper: M.F.A. Ahmed and S.A. Vorobyov, "Collaborative beamforming for
% wireless sensor networks with Gaussian distributed sensor nodes," IEEE
% Trans. Wireless Communications, vol. 8, no. 2, pp.638-643, Feb. 2009.
% Fig 5: The CCDF of a sample beampattern as a function of N for both
% uniform and Gaussian spatial distributions: ? = pi/4 and R = 3 sigma = 2.
% 
% 
% N : Number of sensor nodes
% R : Cluster radius
% V : Vairiance of the Gaussian spatial distribution corresponding to
% cluster radius R
% phi : The azimuth angle.
% P0 : Power level.
% P0dB : Power level in dB.
% CCDF_prec : The precise CCDF of the beampattern level defined for Uniform and Gaussian
% spatial distributions.
% CCDF_RayleighApp : The approx. CCDF of the beampattern level defined for Uniform and Gaussian
% spatial distributions.




clc;clear;
N = 10.^[(0:.05:6)]; 
R = 2;
V = (R^2)/9;

phi = pi/4;


P0=0.1;  
[CCDF_prec_u1,CCDF_prec_g1,CCDF_RayleighApp1]=MyCCDF_N(N,P0,V,phi);

P0=0.01;
[CCDF_prec_u2,CCDF_prec_g2,CCDF_RayleighApp2]=MyCCDF_N(N,P0,V,phi);

P0=0.001;
[CCDF_prec_u3,CCDF_prec_g3,CCDF_RayleighApp3]=MyCCDF_N(N,P0,V,phi);



%   - - - Ploting the figure - - -

%% Create figure
figure1 = figure;
%% Create axes
axes1 = axes(...
    'FontName','Times New Roman',...
    'FontSize',30,...
    'Parent',figure1);
xlabel(axes1,'Power P_0 [dB]');
ylabel(axes1,'CCDF');
grid(axes1,'on');
hold(axes1,'all');

%% Create plot
plot1 = plot(...
    log10(N),CCDF_prec_u1,...
    'LineWidth',2,...
    'LineStyle','--',...
    'Color','b',...
    'MarkerSize',10,...
    'Parent',axes1);

%% Create plot
plot2 = plot(...
    log10(N),CCDF_prec_g1,...
    'Color','r',...
    'LineWidth',2,...
    'MarkerSize',10,...
    'Parent',axes1);

%% Create plot
plot3 = plot(...
    log10(N),CCDF_RayleighApp1,...
    'LineStyle','none',...
    'Color','k',...
    'LineWidth',2,...
    'Marker','x',...
    'MarkerSize',10,...
    'Parent',axes1);
%% Create plot
plot4 = plot(...
    log10(N),CCDF_prec_u2,...
    'LineWidth',2,...
    'LineStyle','--',...
    'Color','b',...
    'MarkerSize',10,...
    'Parent',axes1);

%% Create plot
plot5 = plot(...
    log10(N),CCDF_prec_g2,...
    'Color','r',...
    'LineWidth',2,...
    'MarkerSize',10,...
    'Parent',axes1);

%% Create plot
plot6 = plot(...
    log10(N),CCDF_RayleighApp2,...
    'LineStyle','none',...
    'Color','k',...
    'LineWidth',2,...
    'Marker','x',...
    'MarkerSize',10,...
    'Parent',axes1);
%% Create plot
plot7 = plot(...
    log10(N),CCDF_prec_u3,...
    'LineWidth',2,...
    'LineStyle','--',...
    'Color','b',...
    'MarkerSize',10,...
    'Parent',axes1);

%% Create plot
plot8 = plot(...
    log10(N),CCDF_prec_g3,...
    'Color','r',...
    'LineWidth',2,...
    'MarkerSize',10,...
    'Parent',axes1);

%% Create plot
plot9 = plot(...
    log10(N),CCDF_RayleighApp3,...
    'LineStyle','none',...
    'Color','k',...
    'LineWidth',2,...
    'Marker','x',...
    'MarkerSize',10,...
    'Parent',axes1);

%% Create legend
legend1 = legend(...
    axes1,{' CCDF - Uniform',' CCDF - Gaussian','Rayleigh approximation'},...
    'FontName','Times New Roman',...
    'FontSize',30,...
    'Location','NorthEast');

%% Create xlabel
xlabel('Log_{10}(N)','FontSize',30,'FontName','Times New Roman');

% Create ylabel
ylabel('CCDF','FontSize',30,'FontName','Times New Roman');

% Create legend
legend(axes1,'show');

% Create textbox
annotation(figure1,'textbox','String',{'P_0 = 0.1'},'FontSize',30,...
    'FontName','Times New Roman',...
    'FitHeightToText','off',...
    'LineStyle','none',...
    'Position',[0.1648 0.5273 0.1648 0.08428]);

% Create textbox
annotation(figure1,'textbox','String',{'P_0 = 0.01'},'FontSize',30,...
    'FontName','Times New Roman',...
    'FitHeightToText','off',...
    'LineStyle','none',...
    'Position',[0.3028 0.5278 0.1648 0.08428]);

% Create textbox
annotation(figure1,'textbox','String',{'P_0 = 0.001'},'FontSize',30,...
    'FontName','Times New Roman',...
    'FitHeightToText','off',...
    'LineStyle','none',...
    'Position',[0.572 0.5272 0.1648 0.08428]);
